# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a52001fd81da1471608ba5423c22db0a406b026ba559c5f12c41084d46e88b4032031915f33cf83af2a948f6ff06486883d2ec035a66606319d513d8cec7709a

test:
  secret_key_base: d3606378635470b53066f59e16be9d833e8083e2551adb404af5688035dd0ba90ef844bb270437c6ecf3ad96ef7b14564c103e38936b35f25c9bd30a79608035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
